steps:
  # Step 1: Install Python dependencies
  - name: 'python:3.12-slim'
    id: 'Install dependencies'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/streamlit-app', '.']

  # Step 3: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args: ['push', 'gcr.io/$PROJECT_ID/streamlit-app']

  # Step 4: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    args: 
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'streamlit-app'
      - '--image=gcr.io/$PROJECT_ID/streamlit-app'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--memory=1Gi'  # Increase memory to 1 GiB
      - '--cpu=1'       # Set CPU limit (optional)

# Images to store in Google Container Registry (GCR)
images:
  - 'gcr.io/$PROJECT_ID/streamlit-app'